### ISSUE TITLE
useAccount does't return the updated value

### ISSUE THREAD

**Issue by karol-majewski** [lukezirngibl/msal-react-v2#1]
Hello and thank you for your work!

I configured my `<AuthProvider />` and added it to my application. It works fine, and I'm able to log in with my Microsoft account.

The problem is the `useAccount` function. For some reason, it never contains the actual state variable used by `Account.Provider`. Even when I'm logged in and my account is there in the context, `useAccount` still throws.

Do you have an idea about why that is? Does `useAccount` work for you?

**Comment by lukezirngibl** [comment]
Hey there, sorry for the delayed response. I'll look into this today

**Comment by karol-majewski** [comment]
Hey, I found the issue and it's embarrassing: I was calling `useAccount` in a component that lived outside the authentication context.

It didn't strike me at first because I thought React warns about consuming a context when you're outside its provider, apparently I was wrong.
