### ISSUE TITLE
Return Error 

### ISSUE THREAD

**Issue by adomrockie** [lukezirngibl/msal-react-v2#2]
Thanks got mine to work nicely, need the error message to create a Forgotten password flow. You did not return the error message in your code.

Alternatively you can add a forgotten password flow in your code to complete as below
https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp/blob/master/JavaScriptSPA/authRedirect.js

**Comment by lukezirngibl** [comment]
@adomrockie 

you mean adding this part:

```ts
   // Check for forgot password error
    // Learn more about AAD error codes at https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-aadsts-error-codes
    if (error.errorMessage.indexOf("AADB2C90118") > -1) {
      try {
        // Password reset policy/authority
        myMSALObj.loginRedirect(b2cPolicies.authorities.forgotPassword);
      } catch(err) {
        console.log(err);
      }
    }
```

Could you take a stab at inserting and testing this?

**Comment by adomrockie** [comment]
Yes, currently i am looking at the uri for this error code and handling this outside your code. I will close this as I have a fix outside your code. Thanks
